# Generated by Django 5.0.6 on 2024-06-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
