version: '3.9'
services:
  django_app:
    build: .
    image: django_app:1.0
    volumes:
      - ./myproject:/django_folder
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    container_name: django_container
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DB_HOST=django_mysql_container
      - DB_NAME=django_db
      - DB_USER=root
      # - DB_PASS=''
      - DEBUG=1
    depends_on:
      django_mysql:
        condition: service_healthy

  nginx:
    build: 
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  django_mysql:
    image: mysql:8.4
    container_name: django_mysql_container
    environment:
      MYSQL_DATABASE: 'django_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  data:
